### ISSUE TITLE
Rainbow Question Mark

### ISSUE THREAD

**Issue by Cheetagrl** [Kasax007/Modpack-Development#12]
Hi Hi! I just launched this mudpack on my server, and every time we die, a rainbow question mark appears in our inventory. I am not sure what it is supposed to be? I have been tossing them out. I would also like to request possible the storage drawers (not sure if its available via fabric). Or if its on there, im sorry, maybe I just havnt unlocked it yet :) 
Looks fun and is fun so far though!

**Comment by Kasax007** [comment]
Hey, good to hear you enjoy the modpack so far.
I had storage drawers added in the past but at some point had to remove them because of issues. Hopefully, those are fixed now and I can add the mod back with the next update. 
Regarding the question mark, it's from some mod in the pack and probably used for some crafts. You can use JEI to see what it is used for in crafting. 
The primary application of mysteries, apart from being pretty, is making mystery arrows from plain arrows. Mystery arrows are really quite useful. Shoot one at a block, and it changes. Shoot one at a creature, and it morphs.

**Comment by Kasax007** [comment]
Also, there is a mod called Storage Cabinet that is similar to Storage Drawers that you might wanna have a look at  :)
