### ISSUE TITLE
Fresh server crash on startup

### ISSUE THREAD

**Issue by Djenkan** [Kasax007/Modpack-Development#2]
Hi

I tried setting up a fresh Dreamcraft 1.18.1 v3 server following the instructions in the readme.txt
But it crashes, i have tried reinstalling the server to no avail. I also have java 17.0.1 installed + the client has no problem running.

[latest.log](https://github.com/Kasax007/Modpack-Development/files/7739175/latest.log)

Any help?

**Comment by Kasax007** [comment]
Hey thanks for reporting this issue. This seems to be caused by the mod mystic mounts. For now I would suggest just removing the mod form the server which should fix the issue for now. V3 is worth it to play with all the new structures. In the meantime I will try and find a fix so you can add the mod again. 
Sorry for the inconvenience

**Comment by Kasax007** [comment]
Yeah, actually that also won't do the trick. Very strange. I am afraid the server pack won't be available for v3 until I found the issue.

**Comment by Kasax007** [comment]
V4 Done and publishing rn!
